### ISSUE TITLE
Crashes with NullPointerExcetion any time

### ISSUE THREAD

**Issue by dvalter** [crdroidandroid/android_packages_apps_WallpaperPicker2#1]
Crashes when I select any image from WallpaperPicker (either from bundled wallpapers or my images). 
It's only possible to change wallpaper via another app (i.e. `set as` option in Gallery)

```
03-09 01:15:24.491  7651  7651 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d1a8781
03-09 01:15:24.562  7651  7651 D AndroidRuntime: Shutting down VM
03-09 01:15:24.562  7651  7651 E AndroidRuntime: FATAL EXCEPTION: main
03-09 01:15:24.562  7651  7651 E AndroidRuntime: Process: com.android.wallpaper, PID: 7651
03-09 01:15:24.562  7651  7651 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object float[].clone()' on a null object reference
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at android.graphics.drawable.GradientDrawable.getCornerRadii(GradientDrawable.java:268)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at com.android.wallpaper.picker.PreviewFragment.onCreateView(PreviewFragment.java:289)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2612)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:874)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1228)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1293)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2066)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1856)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-09 01:15:24.562  7651  7651 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
03-09 01:15:24.565  1775  7726 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
03-09 01:15:24.566  1775  2794 W ActivityTaskManager:   Force finishing activity com.android.wallpaper/.picker.PreviewActivity
03-09 01:15:24.569  1775  2794 W ActivityTaskManager:   Force finishing activity com.android.wallpaper/.picker.individual.IndividualPickerActivity
03-09 01:15:24.572  7651  7651 I Process : Sending signal. PID: 7651 SIG: 9
```

Device: pioneer
Version: 6.3 (latest binary/built from source)

**Comment by dvalter** [comment]
For whatever reason (I guess due to internals of `getCornerRadii`) the only working way to bypass NPE I could find is catching this exception.
```patch
diff --git a/src/com/android/wallpaper/picker/PreviewFragment.java b/src/com/android/wallpaper/picker/PreviewFragment.java
index d0d8202..312178a 100755
--- a/src/com/android/wallpaper/picker/PreviewFragment.java
+++ b/src/com/android/wallpaper/picker/PreviewFragment.java
@@ -227,12 +227,16 @@ public abstract class PreviewFragment extends Fragment implements
         // Workaround as we don't have access to bottomDialogCornerRadius, mBottomSheet radii are
         // set to dialogCornerRadius by default.
         GradientDrawable bottomSheetBackground = (GradientDrawable) mBottomSheet.getBackground();
-        float[] radii = bottomSheetBackground.getCornerRadii();
-        for (int i = 0; i < radii.length; i++) {
-            radii[i]*=2f;
+        try {
+            float[] radii = bottomSheetBackground.getCornerRadii();
+            for (int i = 0; i < radii.length; i++) {
+                radii[i]*=2f;
+            }
+            bottomSheetBackground = ((GradientDrawable)bottomSheetBackground.mutate());
+            bottomSheetBackground.setCornerRadii(radii);
+        } catch (NullPointerException npe) {
+           Log.e(TAG, "cornerRadii not available", npe);
         }
-        bottomSheetBackground = ((GradientDrawable)bottomSheetBackground.mutate());
-        bottomSheetBackground.setCornerRadii(radii);
         mBottomSheet.setBackground(bottomSheetBackground);
 
         mBottomSheetInitialState = (savedInstanceState == null) ? STATE_EXPANDED
```
